[build-system]
requires = ["setuptools>=77.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "maxsmooth"
version = "1.2.4"
description = "Derivative-constrained function fitting."
readme = "README.rst"
requires-python = ">=3.10"
dependencies = [
    'matplotlib',
    'numpy',
    'CVXOPT',
    'scipy',
    'progressbar',
]

[tool.setuptools.packages.find]
where = ["."]
include = ["maxsmooth*"]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "pre-commit",
    "packaging"
]
docs = [
  'sphinx', 
  'sphinx_rtd_theme', 
  'numpydoc'
]